"""
Orderbook Decoder

Decodes JSON data into orderbook-layer vectors for the RTL test controller.
"""

from pathlib import Path
from typing import Dict, Any, List

from base_decoder import BaseDecoder


class OrderbookDecoder(BaseDecoder):
    """Decoder for orderbook layer test vectors."""

    _ADD_TYPES = {"A", "F"}
    _DECREMENT_TYPES = {"X", "D", "E"}

    def _parse_side(self, value: Any) -> int:
        """Map side to BID=0, ASK=1."""
        side = str(value).strip().upper()
        if side in {"B", "BID", "0"}:
            return 0
        if side in {"S", "A", "ASK", "1"}:
            return 1
        raise ValueError(f"Unsupported side value: {value}")

    def _parse_price(self, value: Any) -> int:
        """Convert price to integer cents (e.g., 280.00 -> 28000)."""
        if isinstance(value, str):
            cleaned = value.replace("$", "").replace(",", "").strip()
            price_float = float(cleaned)
        else:
            price_float = float(value)
        return int(round(price_float * 100))

    def _build_vectors(self, json_data: List[Dict[str, Any]]) -> List[Dict[str, int]]:
        """Build side/price/delta vectors from parsed rows."""
        vectors: List[Dict[str, int]] = []

        for row in json_data:
            if not self.validate_row(row):
                print(f"  Warning: Skipping invalid row {row.get('row_number', '?')}")
                continue

            msg_type = str(row["Message Type"]).strip().upper()
            shares = int(row["Shares"])

            if msg_type in self._ADD_TYPES:
                delta_qty = shares
            elif msg_type in self._DECREMENT_TYPES:
                delta_qty = -shares
            else:
                print(
                    f"  Warning: Unsupported message type '{msg_type}' in row {row.get('row_number', '?')}"
                )
                continue

            vector = {
                "side": self._parse_side(row["Side"]),
                "price": self._parse_price(row["Price"]),
                "delta_qty": delta_qty,
                "row_number": int(row["row_number"]),
                "msg_type": msg_type,
            }
            vectors.append(vector)

        return vectors

    def _render_svh(self, vectors: List[Dict[str, int]]) -> str:
        """Render vectors as a SystemVerilog include file."""
        actual_count = len(vectors)
        array_count = max(actual_count, 1)

        lines: List[str] = []
        lines.append("// Auto-generated by gen_test_vectors/decoders/orderbook_decoder.py")
        lines.append("// Each entry corresponds to one parsed Excel row.")
        lines.append("")
        lines.append(f"localparam int ORDERBOOK_VECTOR_COUNT = {actual_count};")
        lines.append("typedef struct packed {")
        lines.append("    logic               side;")
        lines.append("    logic [31:0]        price;")
        lines.append("    logic [31:0]        delta_qty;")
        lines.append("} orderbook_vec_t;")
        lines.append("")
        lines.append(f"localparam orderbook_vec_t ORDERBOOK_VECTORS [0:{array_count - 1}] = '{{")

        if actual_count == 0:
            lines.append("    '{side: 1'b0, price: 32'd0, delta_qty: 32'h00000000}")
        else:
            for idx, vec in enumerate(vectors):
                comma = "," if idx < actual_count - 1 else ""
                delta_qty = int(vec["delta_qty"])
                delta_u32 = delta_qty & 0xFFFF_FFFF
                delta_literal = f"32'h{delta_u32:08X}"
                lines.append(
                    "    '{{side: 1'b{side}, price: 32'd{price}, delta_qty: {delta_literal}}}{comma}"
                    "  // row {row} ({msg})".format(
                        side=vec["side"],
                        price=vec["price"],
                        delta_literal=delta_literal,
                        comma=comma,
                        row=vec["row_number"],
                        msg=vec["msg_type"],
                    )
                )

        lines.append("};")
        lines.append("")
        return "\n".join(lines)

    def _default_include_path(self) -> Path:
        """Default path for the RTL include file in the repository."""
        repo_root = Path(__file__).resolve().parents[2]
        return repo_root / "hw" / "orderbook" / "src" / "rtl" / "orderbook_vectors_generated.svh"
    
    def decode(self, json_data: List[Dict[str, Any]]) -> List[Path]:
        """
        Decode JSON data and generate orderbook-layer test files.
        
        Args:
            json_data: List of dictionaries with orderbook-related fields
        
        Returns:
            List of paths to generated output files
        """
        output_files = []

        vectors = self._build_vectors(json_data)
        svh_content = self._render_svh(vectors)

        configured_path = self.config.get("output", {}).get("sv_include_path")
        if configured_path:
            svh_output_path = Path(configured_path)
            if not svh_output_path.is_absolute():
                svh_output_path = Path(__file__).resolve().parents[2] / svh_output_path
        else:
            svh_output_path = self._default_include_path()

        svh_output_path.parent.mkdir(parents=True, exist_ok=True)
        self.write_file(svh_output_path, svh_content)
        output_files.append(svh_output_path)
        
        return output_files

    def validate_row(self, row: Dict[str, Any]) -> bool:
        """Validate required fields for orderbook vector generation."""
        required_fields = ["Message Type", "Side", "Shares", "Price"]
        for field in required_fields:
            if field not in row or row[field] is None:
                print(f"  Error: Missing required field '{field}' in row {row.get('row_number', '?')}")
                return False
        return True
    

