// Auto-generated by gen_test_vectors/decoders/orderbook_decoder.py
// Each entry corresponds to one parsed Excel row.

localparam int ORDERBOOK_VECTOR_COUNT = 3;
typedef struct packed {
    logic               side;
    logic [31:0]        price;
    logic [31:0]        delta_qty;
} orderbook_vec_t;

localparam orderbook_vec_t ORDERBOOK_VECTORS [0:2] = '{
    '{side: 1'b0, price: 32'd28000, delta_qty: 32'h00000064},  // row 2 (A)
    '{side: 1'b0, price: 32'd28100, delta_qty: 32'h000000C8},  // row 3 (A)
    '{side: 1'b0, price: 32'd28100, delta_qty: 32'hFFFFFF38}   // row 4 (X)
};
